{
 "title": "Kubernetes Container Logs (from VictoriaLogs)",
 "tags": [ "managed_by_configmap" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "ns: *" } },
   { "name": "container_in_ns", "label": "container_in_ns", "query": { "query": "ns: $namespace" } },
   { "name": "limit", "label": "Displayed Logs Limit", "query": "10, 15, 20, 50, 100" },
   { "name": "query", "query": "*" },
   {
    "name": "count_by",
    "query": {
     "query": "{ns=\"$namespace\"} container:=\"$container_in_ns\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Usage Notes, VL GUI Access Notes, & Link to Docs",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "* This is querying VictoriaLogs for `kubernetes container logs` using a LogQL query of this nature: \n  * Parameterized Optimized Query: `_stream: {container=~\"($CONTAINER)\", ns=\"$NAMESPACE\"} AND $QUERY` \n  * Optimized Query: `_stream: {container=~\"(grafana)\", ns=\"observability\"} AND *` \n  * Normal Query: `ns:* AND container:* AND *` \n* Tip: For greater flexibility try accessing Victoria Logs GUI URL directly using: \n  * kubectl port-forward service/vl-victoria-logs-single-server -n=observability 9428:9428 \n  * http://localhost:9428/select/vmui/#/?query=ns%3A+*+AND+container%3A+*+AND+*&g0.range_input=5m&g0.end_input=2025-12-02T19%3A34%3A49&g0.relative_time=last_5_minutes \n* Docs to Learn LogQL: \n  * https://docs.victoriametrics.com/victorialogs/logsql/\n"
   }
  },
  {
   "title": "Counts of Kubernetes Container Logs in Namespace: ${namespace}, for Container(s): ${container_in_ns}",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 18, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "_stream: {container=~\"$container_in_ns\", ns=\"$namespace\"} AND $query | stats count()",
     "legendFormat": "${namespace}_${container_in_ns}"
    }
   ]
  },
  {
   "title": "Count by $count_by",
   "type": "piechart",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "_stream: {container=~\"$container_in_ns\", ns=\"$namespace\"} AND $query | stats by (\"$count_by\") count() c | sort by (c desc) | limit 50",
     "legendFormat": "{{$count_by}}"
    }
   ]
  },
  {
   "title": "Kubernetes Container Logs in Namespace: ${namespace}, for Container(s): ${container_in_ns}",
   "type": "logs",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 23 },
   "targets": [
    {
     "expr": "_stream: {container=~\"$container_in_ns\", ns=\"$namespace\"} AND $query | sort desc | limit $limit"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes Event Logs (from VictoriaLogs)",
 "tags": [ "managed_by_configmap" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "event_ns", "label": "event_namespace", "query": { "query": "event_ns: *" } },
   { "name": "obj_kind", "label": "obj_kind", "query": { "query": "event_ns: $event_ns" } },
   { "name": "limit", "label": "Displayed Logs Limit", "query": "10, 15, 20, 50, 100" },
   { "name": "query", "query": "*" },
   {
    "name": "count_by",
    "query": {
     "query": "{event_ns=\"$event_ns\"} obj_kind:=\"$obj_kind\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Usage Notes, VL GUI Access Notes, & Link to Docs",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "* This is querying VictoriaLogs for `kubernetes event logs` using a LogQL query of this nature: \n  * Parameterized Optimized Query: `_stream: {event_ns=~\"($EVENT_NAMESPACE)\", obj_kind=\"$OBJ_KIND\"} AND $QUERY` \n  * Optimized Query: `_stream: {event_ns=~\"none\", obj_kind=~\"Node\"} AND *`\n  * Normal Query: `event_ns:* AND obj_kind:* AND *` \n* Tip: For greater flexibility try accessing Victoria Logs GUI URL directly using: \n  * kubectl port-forward service/vl-victoria-logs-single-server -n=observability 9428:9428 \n  * http://localhost:9428/select/vmui/#/?query=event_ns%3A+*+AND+obj_kind%3A+*+AND+*&g0.range_input=3h&g0.end_input=2025-12-02T23%3A25%3A10&g0.relative_time=last_3_hours \n* Docs to Learn LogQL: \n  * https://docs.victoriametrics.com/victorialogs/logsql/\n"
   }
  },
  {
   "title": "Counts of Kubernetes Event Logs in Namespace: ${event_ns}, for Objects of Kind(s): ${obj_kind}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "_stream: {event_ns=~\"$event_ns\", obj_kind=~\"$obj_kind\"} AND $query | stats count()",
     "legendFormat": "${event_ns}_${obj_kind}"
    }
   ]
  },
  {
   "title": "Count by $count_by",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "_stream: {event_ns=~\"$event_ns\", obj_kind=\"$obj_kind\"} AND $query | stats by (\"$count_by\") count() c | sort by (c desc) | limit 50",
     "legendFormat": "{{$count_by}}"
    }
   ]
  },
  {
   "title": "Kubernetes Event Logs in Namespace: ${event_ns}, associated with objects of Kind(s): ${obj_kind}",
   "type": "logs",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "_stream: {event_ns=~\"$event_ns\", obj_kind=\"$obj_kind\"} AND $query | sort desc | limit $limit"
    }
   ]
  }
 ]
}