import { Easy_EKS_Config_Data } from '../Easy_EKS_Config_Data';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as cdk from 'aws-cdk-lib';
import * as eks from 'aws-cdk-lib/aws-eks';
import { Construct } from "constructs";
import * as fs from 'fs'; //node.js built in file system module
import * as yaml from 'js-yaml'; //npm install js-yaml && npm install --save-dev @types/js-yaml
import { read_yaml_string_as_javascript_object, read_yaml_file_as_javascript_object, read_yaml_file_as_array_of_javascript_objects } from '../../lib/Utilities';
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
export function deploy_victoria_logs_db(stack: cdk.Stack, cluster: eks.ICluster, config: Easy_EKS_Config_Data, observability_namespace: eks.KubernetesManifest){
    const victoria_logs_helm_release = new eks.HelmChart(stack, 'victoria-logs-db-helm', {
        cluster: cluster,
        namespace: 'observability',
        repository: "https://victoriametrics.github.io/helm-charts/",
        chart: "victoria-logs-single",
        release: 'vl',
        version: "0.11.15", //version of helm chart (v0.11.15, maps to app version 1.36.1)
        // helm repo add vm https://victoriametrics.github.io/helm-charts/
        // helm repo update vm
        // helm search repo vm
        values: {
            "server": {
                //v--PURPOSEFULLY not using pod level HTTPS, because it breaks kubectl port-forward
                // "extraVolumes": [{
                //     "name": "https-cert",
                //     "secret": {
                //         "secretName": "https-cert-for-vl-victoria-logs-single-server" //generated by cert-manager
                //     },
                // }],
                // "extraVolumeMounts": [{
                //     "name": "https-cert",
                //     "mountPath": "/etc/ssl/certs",
                //     "readOnly": true,
                // }],
                // "service": {
                //     "servicePort": "9443", //unencrypted default is 9428
                //     "targetPort": "9443",
                // },
                "extraArgs": { //https://docs.victoriametrics.com/victorialogs/#list-of-command-line-flags
                    "httpListenAddr": ":9428",
                    "tls": "false", //tls: true, breaks kubectl port-forward
                    //"tlsCertFile": "/etc/ssl/certs/tls.crt",
                    //"tlsKeyFile": "/etc/ssl/certs/tls.key",
                    "enableTCP6": `${config.ipMode === eks.IpFamily.IP_V6}`, //defaults to true, which enables application level IPv6 support.
                },  //^-- This is required for readiness and liveness probes to work correctly in IPv6 environments.
                "retentionPeriod": "30d",
                "persistentVolume": {
                    "size": "10Gi"
                },
                "resources": {
                    "requests": {
                        "cpu": "100m",
                        "memory": "128Mi",
                    },
                    "limits": {
                        "memory": "4Gi",
                    },
                },
            },
        },//end helm values
        //Command to verify config:
        //* helm get values vl -n=observability
        //Access Proxy Command:
        //* kubectl port-forward service/vl-victoria-logs-single-server -n=observability 9428:9428
        //Browser Access:
        //* http://localhost:9428/select/vmui/
    });
    // Imperative installation order to avoid temporary errors in logs
    victoria_logs_helm_release.node.addDependency(observability_namespace);

} //end deploy_victoria_logs_db()
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
