import { Easy_EKS_Config_Data } from '../Easy_EKS_Config_Data';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as cdk from 'aws-cdk-lib';
import * as eks from 'aws-cdk-lib/aws-eks';
import { Construct } from "constructs";
import * as fs from 'fs'; //node.js built in file system module
import * as yaml from 'js-yaml'; //npm install js-yaml && npm install --save-dev @types/js-yaml
import { read_yaml_string_as_javascript_object, read_yaml_file_as_javascript_object, read_yaml_file_as_array_of_javascript_objects } from '../../lib/Utilities';
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
export function deploy_vector_observability_agents(stack: cdk.Stack, cluster: eks.ICluster, config: Easy_EKS_Config_Data, observability_namespace: eks.KubernetesManifest){


const vector_observability_agent_helm_values_as_yaml = `
role: Agent     #<--deploys vector as a kubernetes daemonset & uses hostPath for ephemeral filesystem.
logLevel: "info"
image:
  base: distroless-libc
rollWorkloadSecrets: true
resources:
  limits:
    memory: 4Gi
  requests:
    cpu: 10m
    memory: 32Mi
env:
- name: KUBERNETES_SERVICE_HOST
  value: "kubernetes.default.svc"   #<--IPv6 fix documented in https://github.com/vectordotdev/vector/issues/19224
containerPorts:
- containerPort: 8686   #<--graphql endpoint. Enabled by customConfig.api.enabled: true & address: [::]:8686
  name: api             #   Usage: kubectl exec -it daemonset/observability-agent-vector -n=observability -- vector top -H
  protocol: TCP         #   ^-- shows a metric dashboard
- containerPort: 9090   #<--prometheus metric http endpoint. Enabled by customConfig.sinks.exporter.type = prometheus_exporter
  name: prom-exporter   #   Usage: kubectl port-forward svc/observability-agent-vector 9090:9090 -n=observability
  protocol: TCP         #   ^-- Browser: localhost:9090/metrics
service:
  ports:
  - name: api
    port: 8686
    protocol: TCP
  - name: prom-exporter
    port: 9090
    protocol: TCP
serviceHeadless:
  ports:
  - name: api
    port: 8686
    protocol: TCP
  - name: prom-exporter
    port: 9090
    protocol: TCP
extraVolumes:
- name: ca-of-https-cert
  secret:
    secretName: root-ca-for-frugal-observability-stack
extraVolumeMounts:
- name: ca-of-https-cert
  mountPath: /etc/ssl/certs/ca.crt 
  subPath: ca.crt #mounting a subset of the secret
  readOnly: true
customConfig:
  acknowledgements:  #<--(durable delivery of data) means: send data, ask server to verify/acknowledge successful delivery, retry upon failure.
    enabled: true    #Note it's often not supported,  but it'll be enabled for sinks where it is supported.
  api:
    enabled: true
    address: "[::]:8686"  #<-- triggers listening on port 8686, accessible from the IPv6 equivalent of 0.0.0.0 (any source IP)
    playground: false
  data_dir: /vector-data-dir
  sources:
    worker_node_metrics:
      type: host_metrics
      namespace: kube_worker_node_metrics
      filesystem:
        devices:
          excludes:
          - 'binfmt_misc'
        filesystems:
          excludes:
          - '[binfmt_misc]'
        mountpoints:
          excludes:
          - '*/proc/sys/fs/binfmt_misc'
    container_logs:
      type: kubernetes_logs  #(<-- logs of containers of kubernetes pods)
      glob_minimum_cooldown_ms: 1000
  sinks: #<--(sink = destination)
    prometheus_exporter:          #<-- You can test using kubectl port-forward -n=observability svc/observability-aggregator-vector 9090:9090
      type: prometheus_exporter   #    Then browser: http://localhost:9090/metrics
      address: "[::]:9090" #<-- triggers listening on port 9090
      inputs:
      - worker_node_metrics
    vector_aggregator:
      type: vector  #<--Uses efficient gRPC & End-to-End Ack (retry on fail) for data durability
      address: "https://observability-aggregator-vector.observability:6443"   #<--inner cluster dns name (generated by kube service)
      tls:
        enabled: true
        ca_file: /etc/ssl/certs/ca.crt
        server_name: observability-aggregator-vector.observability
        verify_hostname: true
        verify_certificate: true
      healthcheck:
        enabled: true
      compression: true
      buffer:        #Note: In theory statefulset aggregator hosted on spot nodes can reboot without losing observability data, thanks to buffer
      - type: disk                   #<--node local disk (via hostPath)
        max_size: ${2 * 1073741824}  #<--2 GiB
        when_full: drop_newest       #<--last resort
      inputs: #(to send to aggregator)
      - container_logs
      - worker_node_metrics
`;
const vector_observability_agent_helm_values_as_JS_object: JSON = read_yaml_string_as_javascript_object(vector_observability_agent_helm_values_as_yaml);

const vector_observability_aggregator_helm_values_as_yaml = `
role: Aggregator    #<--deploys vector as a kubernetes statefulset & uses PVC for buffering.
logLevel: "info"
image:
  base: distroless-libc
# ^-- Explanation of what image.base options does:
# alpine          --use the following image--> 0.38.0-alpine
# distroless-libc --use the following image--> 0.38.0-distroless-libc
# Notes: 
# * 0.38.0 is used as an explicit example, but it's real value would be the default image version associated with the helm chart version
# * distroless-libc is better in terms of performance and security, recommend to use it after figuring out an ideal config.
# * alpine is useful if you need to debug config, as it allows exec'ing into the pod
#   Note installing apps is a bit tricky in their alpine image, so here's an example of how to install additional tools
#   * kubect exec -it pod/observability-aggregator-vector-0 -n=observability -- /bin/ash
#     Pod's Alpine Shell:
#     * apk update --no-check-certificate --allow-untrusted
#     * apk add --no-cache --no-check-certificate --allow-untrusted netcat-openbsd
#     * nc -6 -w 1 -v -z observability-aggregator-vector.observability 6443
#     * apk add --no-cache --no-check-certificate --allow-untrusted curl
#     * curl observability-aggregator-vector.observability:8686/health 
rollWorkloadSecrets: true
replicas: 1
resources:
  limits:
    memory: 4Gi
  requests:
    cpu: 10m
    memory: 32Mi
env:
- name: KUBERNETES_SERVICE_HOST
  value: "kubernetes.default.svc"   #<--IPv6 fix documented in https://github.com/vectordotdev/vector/issues/19224
containerPorts:
- containerPort: 6443   #<--GRPC endpoint. (not a webserver) (grpc needs https)
  name: vector
  protocol: TCP
- containerPort: 8686   #<--graphql endpoint. Enabled by customConfig.api.enabled: true & address: [::]:8686
  name: api             #   Usage: kubectl exec -it pod/observability-aggregator-vector-0 -n=observability -- vector top -H
  protocol: TCP         #   ^-- shows a metric dashboard
- containerPort: 9090   #<--prometheus metric http endpoint. Enabled by customConfig.sinks.exporter.type = prometheus_exporter
  name: prom-exporter   #   Usage: kubectl port-forward svc/observability-aggregator-vector 9090:9090 -n=observability
  protocol: TCP         #   ^-- Browser: localhost:9090/metrics
service:
  ports:
  - name: vector
    port: 6443
    protocol: TCP
  - name: api
    port: 8686
    protocol: TCP
  - name: prom-exporter
    port: 9090
    protocol: TCP
serviceHeadless:
  ports:
  - name: vector
    port: 6443
    protocol: TCP
  - name: api
    port: 8686
    protocol: TCP
  - name: prom-exporter
    port: 9090
    protocol: TCP
extraVolumes:
- name: https-cert
  secret:
    secretName: https-cert-for-observability-aggregator-vector    #<--(contains: ca.crt, tls.crt, tls.key)
extraVolumeMounts:
- name: https-cert
  mountPath: /etc/ssl/certs
  readOnly: true
customConfig:
  acknowledgements:   #<--(durable delivery of data) means: send data, ask server to verify/acknowledge successful delivery, retry upon failure.
    enabled: true
  api:
    enabled: true
    address: "[::]:8686"  #<-- triggers listening on port 8686, accessible from the IPv6 equivalent of 0.0.0.0 (any source IP)
    playground: false
  data_dir: /vector-data-dir
  sources:
    vector_agents: #<-- source of container logs + worker node metrics
      type: vector
      version: "2"
      address: "[::]:6443"   #<-- triggers listening on port 6443 (from an IPv6 IP address)
      tls:
        enabled: true
        ca_file: /etc/ssl/certs/ca.crt
        crt_file: /etc/ssl/certs/tls.crt
        key_file: /etc/ssl/certs/tls.key
        server_name: observability-aggregator-vector.observability
        verify_certificate: false    #<-- (false = mTLS disabled) (client cert verification true = mTLS enabled)
        verify_hostname: true        #<-- true = only allow incoming traffic from dns names associated with https-cert
    vector_aggregator_generated_test_logs:
      type: demo_logs
      format: shuffle # randomly choose a line in the list
      lines:
      - "test log #1"
      - "test log #2"
      - "test log #3"
      interval: 10 #<-- generate 1 test log every 10 seconds
    vector_aggregator_generated_test_metrics:
      type: static_metrics
      namespace: vector_generated_test_metric
      interval_secs: 10  #<-- generate 1 test metric every 10 seconds
      metrics:
      - name: vector_aggregator_generated_test_metric
        kind: absolute
        value:
          gauge:
            value: 1
        tags:
          purpose: testing
  transforms:
    from_vector_agents:
      type: "route"
      inputs: [ "vector_agents" ]
      route:
        metrics: #<-- now "from_vector_agents.metrics" is a recognized input
          type: 'is_metric'
        logs:    #<-- now "from_vector_agents.logs" is a recognized input
          type: 'is_log'
        traces:  #<-- now "from_vector_agents.traces" is a recognized input
          type: 'is_trace'
      reroute_unmatched: false
    subset_of_metrics:
      type: "route"
      inputs: 
      - from_vector_agents.metrics
      - vector_aggregator_generated_test_metrics
      route: #v-- Pattern is log_name: 'VRLcondition' (https://vector.dev/docs/reference/vrl/#example-filtering-events)
        vector_aggregator_generated_test_metrics: '.namespace == "vector_generated_test_metric"'   #<-- now "subset_of_metrics.vector_aggregator_generated_test_metrics" is a recognized input
        kube_worker_node_metrics: '.namespace == "kube_worker_node_metrics"'                       #<-- now "subset_of_metrics.kube_worker_node_metrics" is a recognized input
    subset_of_logs:
      type: "route"
      reroute_unmatched: false
      inputs: 
      - from_vector_agents.logs
      - vector_aggregator_generated_test_logs
      route: #v-- Pattern is log_name: 'VRLcondition' (https://vector.dev/docs/reference/vrl/#example-filtering-events)
        vector_aggregator_generated_test_logs: '.source_type == "demo_logs"'   #<-- now "subset_of_logs.vector_aggregator_generated_test_logs" is a recognized input
        kubernetes_event_exporter_container_logs: ' .source_type == "kubernetes_logs" && .kubernetes.pod_labels."app.kubernetes.io/name" == "kubernetes-event-exporter" '     #<-- now "subset_of_logs.kubernetes_event_exporter_container_logs" is a recognized input
        kube_container_logs: ' .source_type == "kubernetes_logs" && .kubernetes.pod_labels."app.kubernetes.io/name" != "kubernetes-event-exporter" ' #<-- now "subset_of_logs.kube_container_logs" is a recognized input
    kube_event_logs:
      type: "remap"
      inputs: [ subset_of_logs.kubernetes_event_exporter_container_logs ]
      # v-- source represents an embedded multi-line text file / HEREDOC of vector remap language syntax
      source: |
        . = parse_json!(.message) #<-- extract contents of json log embedded in .message, and transfer it's contents into the root of a new json log entry
    conventionalized_kube_container_logs:
      type: "remap"
      inputs: [ "subset_of_logs.kube_container_logs" ]
      source: |
        # v-- Thanks to this "log_source: kubernetes_container_logs" becomes a working query for Victoria Logs  
        .log_source = "kubernetes_container_logs"
        # v-- UX improvements
        .cluster_name = "${config.cluster_name}"
        .cluster_region = "${config.cluster_region}"
        #v-- shortening name of keys used as log streams, for UX reasons (looks nicer in GUI)
        .container = del(.kubernetes.container_name) #<-- effectively renames the key "kubernetes.container_name" to "container"
        .ns = del(.kubernetes.pod_namespace) #<-- effectively renames the key "kubernetes.pod_namespace" to "ns"
        # v-- Cleaning up duplicate info & useless noise
        del(.source_type)
        del(.file)
        del(.kubernetes.container_id)
        del(.kubernetes.namespace_labels)
        del(.kubernetes.node_labels."k8s.io/cloud-provider-aws")
        del(.kubernetes.node_labels."karpenter.sh/do-not-sync-taints")
        del(.kubernetes.node_labels."beta*")
        del(.kubernetes.node_labels."beta.kubernetes.io/arch")
        del(.kubernetes.node_labels."beta.kubernetes.io/instance-type") #<-- "'s are needed when referencing a key with /'s OR -'s
        del(.kubernetes.node_labels."beta.kubernetes.io/os")
        del(.kubernetes.node_labels."failure-domain.beta.kubernetes.io/region")
        del(.kubernetes.node_labels."failure-domain.beta.kubernetes.io/zone")
        del(.kubernetes.node_labels."topology.ebs.csi.aws.com/zone")
        del(.kubernetes.node_labels."kubernetes.io/os")
        del(.kubernetes.node_labels."kubernetes.io/hostname")
        del(.kubernetes.node_labels."karpenter.sh/initialized")
        del(.kubernetes.node_labels."karpenter.sh/registered")
        del(.kubernetes.node_labels."karpenter.k8s.aws/instance-hypervisor")
        del(.kubernetes.node_labels."karpenter.k8s.aws/instance-family")
        del(.kubernetes.node_labels."karpenter.k8s.aws/instance-generation")
        del(.kubernetes.node_labels."karpenter.k8s.aws/instance-size")
        del(.kubernetes.node_labels."karpenter.k8s.aws/instance-encryption-in-transit-supported")
        del(.kubernetes.node_labels."karpenter.k8s.aws/instance-category")
        del(.kubernetes.node_labels."eks.amazonaws.com/sourceLaunchTemplateVersion")
        del(.kubernetes.pod_ips)
        del(.kubernetes.pod_annotations."eks.amazonaws.com/timestamp")
        del(.kubernetes.pod_labels."controller-revision-hash")
        del(.kubernetes.pod_labels."pod-template-generation")
        del(.kubernetes.pod_labels."pod-template-hash")
        del(.kubernetes.pod_uid)
        # v-- Note: .kubernetes is purposefully temporarily added in front of a few things, to preserve them, when .kubernetes is later removed.
        .kubernetes.message = del(.message)
        .kubernetes.timestamp = del(.timestamp)
        .kubernetes.cluster_name = del(.cluster_name)
        .kubernetes.cluster_region = del(.cluster_region)
        .kubernetes.ns = del(.ns)
        .kubernetes.container = del(.container)
        .kubernetes.log_type = del(.stream)
        .kubernetes.log_source = del(.log_source)
        . = del(.kubernetes) #<-- remove kubernetes for UX as its redundant info
    conventionalized_kube_event_logs:
      type: "remap"
      inputs: [ kube_event_logs ]
      source: |
        # v-- Thanks to this "log_source: kubernetes_event_logs" becomes a working query for Victoria Logs
        .log_source = "kubernetes_event_logs"
        # v-- UX improvements
        .cluster_name = "${config.cluster_name}"
        .cluster_region = "${config.cluster_region}"
        .event_type = del(.type) #<-- effectively renames the key "type" to "event_type"
        .event_reason = del(.reason) #<-- effectively renames the key "reason" to "event_reason"
        if ( exists(.involvedObject.namespace) ) {
            .event_ns = del(.involvedObject.namespace) #<-- effectively renames the key "involvedObject.namespace" to "event_ns"
        } else {
            .event_ns = "none" #<-- force existance of key, so it can be used as Victoria Log Stream Entry
        }   #^v-- shortening name of keys used as log streams, for UX reasons (looks nicer in GUI)
        .obj_kind = del(.involvedObject.kind) #<-- effectively renames the key "involvedObject.kind" to "obj_kind"
        # v-- Cleaning up duplicate info & useless noise
        del(.source_type)
        del(.involvedObject.resourceVersion)
        del(.involvedObject.uid)
        del(.involvedObject.ownerReferences)
        del(.involvedObject.deleted)
        del(.metadata)
        del(.source)
    conventionalized_vector_aggregator_generated_test_logs:
      type: "remap"
      inputs: [ "subset_of_logs.vector_aggregator_generated_test_logs" ]
      source: |-
        del(.source_type) # remove the following KV pair from the log entry, "source_type": "demo_logs"
        .log_source = "vector_generated_test_logs" #(effectively renamed the KV pair, to this new name)
        # ^-- Thanks to this "log_source: vector_generated_test_logs" becomes a working query for Victoria Logs
  sinks: #<--(sink = destination)
#    prometheus_exporter:          #<-- You can test using kubectl port-forward -n=observability svc/observability-aggregator-vector 9090:9090
#      type: prometheus_exporter   #    Then browser: http://localhost:9090/metrics
#      address: "[::]:9090"  #<-- triggers listening on port 9090 (from an IPv6 IP address)
#      inputs:
#      - subset_of_metrics.kube_worker_node_metrics
    victoria_metrics_db_sink_for_conventionalized_metrics:
      type: prometheus_remote_write
      endpoint: http://vm-victoria-metrics-single-server.observability.svc.cluster.local:8428/api/v1/write
      inputs:
      - subset_of_metrics.kube_worker_node_metrics
      healthcheck:
        enabled: false   #<-- recommended per VM's docs: https://docs.victoriametrics.com/victoriametrics/data-ingestion/vector/
      compression: zstd
    victoria_logs_db_sink_for_conventionalized_kube_container_logs:
      endpoints:
      - http://vl-victoria-logs-single-server.observability.svc.cluster.local:9428/insert/elasticsearch/
      inputs: [ conventionalized_kube_container_logs ]  #<-- best to only send 1 input per vl_log_sink, so they can have diff VL-Stream-Field values
      type: elasticsearch   #<-- The Bulk API algorithm invented by elasticsearch is the most efficient option available
      api_version: v8
      compression: gzip
      mode: bulk
      healthcheck:
        enabled: false   #<-- recommended per VL's docs: https://docs.victoriametrics.com/victorialogs/data-ingestion/vector/
      request:  #<-- based on example config of 'helm show values oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single'
        headers: #v--Important: don't put spaces between these CSV values, or it'll cause a hidden error.
          VL-Time-Field: "timestamp"
          VL-Stream-Fields: "container,ns"  #<-- UX wise best to only have short names & 2 max (also only use keys with low cardinality) (query optimization)
          VL-Msg-Field: "message"
          AccountID: "0"
          ProjectID: "0"
    victoria_logs_db_sink_for_conventionalized_kube_event_logs:
      inputs: [ conventionalized_kube_event_logs ]  #<-- best to only send 1 input per vl_log_sink, so they can have diff VL-Stream-Field values
      type: elasticsearch   #<-- The Bulk API algorithm invented by elasticsearch is the most efficient option available
      api_version: v8
      compression: gzip
      mode: bulk
      endpoints:
      - http://vl-victoria-logs-single-server:9428/insert/elasticsearch/
      healthcheck:
        enabled: false   #<-- recommended per VL's docs: https://docs.victoriametrics.com/victorialogs/data-ingestion/vector/
      request:  #<-- based on example config of 'helm show values oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single'
        headers: #v--Important: don't put spaces between these CSV values, or it'll cause a hidden error.
          VL-Time-Field: "timestamp"
          VL-Stream-Fields: "obj_kind,event_ns"  #<-- UX wise best to only have short names & 2 max (also only use keys with low cardinality) (query optimization)
          VL-Msg-Field: "message"
          AccountID: "0"
          ProjectID: "0"
#    std_out: #<-- You can test using kubectl logs observability-aggregator-vector-0 -n=observability
#      type: "console"
#      inputs:
#      - conventionalized_vector_aggregator_generated_test_logs
#      - subset_of_metrics.vector_aggregator_generated_test_metrics
#      - conventionalized_kube_container_logs
#      encoding:
#        codec: "json"
`;
    const vector_observability_aggregator_helm_values_as_JS_object: JSON = read_yaml_string_as_javascript_object(vector_observability_aggregator_helm_values_as_yaml);

    const vector_aggregator_cert_yaml_file = './lib/Frugal_Observability/manifests/certs_for_vector_observability_aggregator.yaml';
    const vector_aggregator_cert_yamls_as_JSO_array: JSON[] = read_yaml_file_as_array_of_javascript_objects(vector_aggregator_cert_yaml_file);
    const observability_certificates = new eks.KubernetesManifest(stack, "observability-certificates", {
        cluster: cluster,
        manifest: [ ...vector_aggregator_cert_yamls_as_JSO_array ],
        overwrite: true,
        prune: true,
    });
    observability_certificates.node.addDependency(observability_namespace);



    const vector_observability_agent_helm_release = new eks.HelmChart(stack, 'vector-observability-agent-daemonset-helm', {
        cluster: cluster,
        namespace: 'observability',
        repository: 'https://helm.vector.dev',
        chart: 'vector',
        release: 'observability-agent',
        version: '0.46.0', //version of helm chart (0.46.0, maps to app version 0.50.0-distroless-libc)
        // helm repo add vector https://helm.vector.dev
        // helm repo update vector
        // helm search repo vector
        // helm show values vector/vector       <-- can be run to show all possible values
        // helm get values observability-agent  <-- can be run to see the yaml equivalent the the below values. (potentially easier to read)
        values: vector_observability_agent_helm_values_as_JS_object,
    });
    vector_observability_agent_helm_release.node.addDependency(observability_namespace);

    const vector_observability_aggregator_helm_release = new eks.HelmChart(stack, 'vector-observability-aggregator-statefulset-helm', {
        cluster: cluster,
        namespace: 'observability',
        repository: 'https://helm.vector.dev',
        chart: 'vector',
        release: 'observability-aggregator', //<-- don't modify as an https cert is generated to match a name generated based on this
        version: '0.46.0', //version of helm chart (0.46.0, maps to app version 0.50.0-distroless-libc)
        // helm repo add vector https://helm.vector.dev
        // helm repo update vector
        // helm search repo vector
        // helm show values vector/vector            <-- can be run to show all possible values
        // helm get values observability-aggregator  <-- can be run to see the yaml equivalent the the below values. (potentially easier to read)
        values: vector_observability_aggregator_helm_values_as_JS_object,
    });
    vector_observability_aggregator_helm_release.node.addDependency(observability_namespace);
    vector_observability_aggregator_helm_release.node.addDependency(observability_certificates);

} //end deploy_vector_observability_agents()

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
