# Referenced by:
# * ./config/baseline_envs_eks_config.ts's deploy_essentials()
#   which:
#   * Does last min injection of value into variable of this templatized_helm_values.yaml file
#     (templatized variable injection occurs for cluster_name & cluster_region)
#   * stores it into a Javascript config object
# * ./lib/Frugal_Observability/deploy_vm_logs_custom_stack.ts
#   which:
#   * merges the baseline & override helm values
#   * used the merged helm values to deploy
########################################################################################################
# About:
# * This configures vector.dev as an agent to collect, parse, and ship container logs of kubernetes pods
# * There should be no need to change this baseline config
# * The intent is for this to represent a relatively complete (templatized) config, and additional files
#   can be supplied as config overrides.
########################################################################################################
role: Agent     #<--deploys vector as a kubernetes daemonset & uses hostPath for ephemeral filesystem.
logLevel: "info"
image:
  base: distroless-libc
# ^-- Explanation of what image.base options does:
# alpine          --use the following image--> 0.38.0-alpine
# distroless-libc --use the following image--> 0.38.0-distroless-libc
# Notes: 
# * 0.38.0 is used as an explicit example, but it's real value would be the default image version associated with the helm chart version
# * distroless-libc is better in terms of performance and security, recommend to use it after figuring out an ideal config.
# * alpine is useful if you need to debug config, as it allows exec'ing into the pod
#   Note installing apps is a bit tricky in their alpine image, so here's an example of how to install additional tools
#   * kubect exec -it daemonset/log-collection-agent-vector -n=observability -- /bin/ash
#     Pod's Alpine Shell:
#     * apk update --no-check-certificate --allow-untrusted
#     * apk add --no-cache --no-check-certificate --allow-untrusted netcat-openbsd
#     * nc -6 -w 1 -v -z vmks-grafana.observability 80
#     * apk add --no-cache --no-check-certificate --allow-untrusted curl
#     * curl vmks-grafana.observability:80
rollWorkloadSecrets: true
podPriorityClassName: "system-node-critical" #ensures daemonset is schedulable even on small nodes
resources:
  limits:
    memory: 4Gi
  requests:
    cpu: 10m
    memory: 64Mi
env:
- name: KUBERNETES_SERVICE_HOST
  value: "kubernetes.default.svc"   #<--IPv6 fix documented in https://github.com/vectordotdev/vector/issues/19224
containerPorts:
- containerPort: 8686   #<--graphql endpoint. Enabled by customConfig.api.enabled: true & address: [::]:8686
  name: api             #   Usage: kubectl exec -it daemonset/observability-agent-vector -n=observability -- vector top -H
  protocol: TCP         #   ^-- shows a metric dashboard
service:
  ports:
  - name: api
    port: 8686
    protocol: TCP
serviceHeadless:
  ports:
  - name: api
    port: 8686
    protocol: TCP
customConfig:
  acknowledgements:  #<--(durable delivery of data) means: send data, ask server to verify/acknowledge successful delivery, retry upon failure.
    enabled: true    #Note it's often not supported,  but it'll be enabled for sinks where it is supported.
  api:
    enabled: true
    address: "[::]:8686"  #<-- triggers listening on port 8686, accessible from the IPv6 equivalent of 0.0.0.0 (any source IP)
    playground: false
  data_dir: /vector-data-dir
  sources:
    container_logs:
      type: kubernetes_logs  #(<-- logs of containers of kubernetes pods)
      glob_minimum_cooldown_ms: 1000
  transforms:
    subset_of_logs:
      type: "route"
      reroute_unmatched: false
      inputs: 
      - container_logs
      route: #v-- Pattern is log_name: 'VRLcondition' (https://vector.dev/docs/reference/vrl/#example-filtering-events)
        kubernetes_event_exporter_container_logs: ' .source_type == "kubernetes_logs" && .kubernetes.pod_labels."app.kubernetes.io/name" == "kubernetes-event-exporter" '     #<-- now "subset_of_logs.kubernetes_event_exporter_container_logs" is a recognized input
        kube_container_logs: ' .source_type == "kubernetes_logs" && .kubernetes.pod_labels."app.kubernetes.io/name" != "kubernetes-event-exporter" ' #<-- now "subset_of_logs.kube_container_logs" is a recognized input
    kube_event_logs:
      type: "remap"
      inputs: [ subset_of_logs.kubernetes_event_exporter_container_logs ]
      # v-- source represents an embedded multi-line text file / HEREDOC of vector remap language syntax
      source: |
        . = parse_json!(.message) #<-- extract contents of json log embedded in .message, and transfer it's contents into the root of a new json log entry
    conventionalized_kube_event_logs:
      type: "remap"
      inputs: [ kube_event_logs ]
      source: |
        # v-- Thanks to this "log_source: kubernetes_event_logs" becomes a working query for Victoria Logs
        .log_source = "kubernetes_event_logs"
        # v-- UX improvements
        .cluster_name = "TEMPLATIZED_VARIABLE_CLUSTER_NAME" #<-- find and replace will occur (using typescript logic)
        .cluster_region = "TEMPLATIZED_VARIABLE_CLUSTER_REGION" #<-- find and replace will occur (using typescript logic)
        .event_type = del(.type) #<-- effectively renames the key "type" to "event_type"
        .event_reason = del(.reason) #<-- effectively renames the key "reason" to "event_reason"
        if ( exists(.involvedObject.namespace) ) {
            .event_ns = del(.involvedObject.namespace) #<-- effectively renames the key "involvedObject.namespace" to "event_ns"
        } else {
            .event_ns = "none" #<-- force existance of key, so it can be used as Victoria Log Stream Entry
        }   #^v-- shortening name of keys used as log streams, for UX reasons (looks nicer in GUI)
        .obj_kind = del(.involvedObject.kind) #<-- effectively renames the key "involvedObject.kind" to "obj_kind"
        # v-- Cleaning up duplicate info & useless noise
        del(.source_type)
        del(.involvedObject.resourceVersion)
        del(.involvedObject.uid)
        del(.involvedObject.ownerReferences)
        del(.involvedObject.deleted)
        del(.metadata)
        del(.source)
    conventionalized_kube_container_logs:
      type: "remap"
      inputs: [ "subset_of_logs.kube_container_logs" ]
      source: |
        # v-- Thanks to this "log_source: kubernetes_container_logs" becomes a working query for Victoria Logs  
        .log_source = "kubernetes_container_logs"
        # v-- UX improvements
        .cluster_name = "TEMPLATIZED_VARIABLE_CLUSTER_NAME" #<-- find and replace will occur (using typescript logic)
        .cluster_region = "TEMPLATIZED_VARIABLE_CLUSTER_REGION" #<-- find and replace will occur (using typescript logic)
        #v-- shortening name of keys used as log streams, for UX reasons (looks nicer in GUI)
        .container = del(.kubernetes.container_name) #<-- effectively renames the key "kubernetes.container_name" to "container"
        .ns = del(.kubernetes.pod_namespace) #<-- effectively renames the key "kubernetes.pod_namespace" to "ns"
        # v-- Cleaning up duplicate info & useless noise
        del(.source_type)
        del(.file)
        del(.kubernetes.container_id)
        del(.kubernetes.namespace_labels)
        del(.kubernetes.node_labels."k8s.io/cloud-provider-aws")
        del(.kubernetes.node_labels."karpenter.sh/do-not-sync-taints")
        del(.kubernetes.node_labels."beta*")
        del(.kubernetes.node_labels."beta.kubernetes.io/arch")
        del(.kubernetes.node_labels."beta.kubernetes.io/instance-type") #<-- "'s are needed when referencing a key with /'s OR -'s
        del(.kubernetes.node_labels."beta.kubernetes.io/os")
        del(.kubernetes.node_labels."failure-domain.beta.kubernetes.io/region")
        del(.kubernetes.node_labels."failure-domain.beta.kubernetes.io/zone")
        del(.kubernetes.node_labels."topology.ebs.csi.aws.com/zone")
        del(.kubernetes.node_labels."kubernetes.io/os")
        del(.kubernetes.node_labels."kubernetes.io/hostname")
        del(.kubernetes.node_labels."karpenter.sh/initialized")
        del(.kubernetes.node_labels."karpenter.sh/registered")
        del(.kubernetes.node_labels."karpenter.k8s.aws/instance-hypervisor")
        del(.kubernetes.node_labels."karpenter.k8s.aws/instance-family")
        del(.kubernetes.node_labels."karpenter.k8s.aws/instance-generation")
        del(.kubernetes.node_labels."karpenter.k8s.aws/instance-size")
        del(.kubernetes.node_labels."karpenter.k8s.aws/instance-encryption-in-transit-supported")
        del(.kubernetes.node_labels."karpenter.k8s.aws/instance-category")
        del(.kubernetes.node_labels."eks.amazonaws.com/sourceLaunchTemplateVersion")
        del(.kubernetes.pod_ips)
        del(.kubernetes.pod_annotations."eks.amazonaws.com/timestamp")
        del(.kubernetes.pod_labels."controller-revision-hash")
        del(.kubernetes.pod_labels."pod-template-generation")
        del(.kubernetes.pod_labels."pod-template-hash")
        del(.kubernetes.pod_uid)
        # v-- Note: .kubernetes is purposefully temporarily added in front of a few things, to preserve them, when .kubernetes is later removed.
        .kubernetes.message = del(.message)
        .kubernetes.timestamp = del(.timestamp)
        .kubernetes.cluster_name = del(.cluster_name)
        .kubernetes.cluster_region = del(.cluster_region)
        .kubernetes.ns = del(.ns)
        .kubernetes.container = del(.container)
        .kubernetes.log_type = del(.stream)
        .kubernetes.log_source = del(.log_source)
        . = del(.kubernetes) #<-- remove kubernetes for UX as its redundant info
  sinks: #<--(sink = destination)
    victoria_logs_db_sink_for_conventionalized_kube_container_logs:
      endpoints:
      - http://vl-victoria-logs-single-server.observability.svc.cluster.local:9428/insert/elasticsearch/
      inputs: [ conventionalized_kube_container_logs ]  #<-- best to only send 1 input per vl_log_sink, so they can have diff VL-Stream-Field values
      type: elasticsearch   #<-- The Bulk API algorithm invented by elasticsearch is the most efficient option available
      api_version: v8
      compression: gzip
      mode: bulk
      healthcheck:
        enabled: false   #<-- recommended per VL's docs: https://docs.victoriametrics.com/victorialogs/data-ingestion/vector/
      request:  #<-- based on example config of 'helm show values oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single'
        headers: #v--Important: don't put spaces between these CSV values, or it'll cause a hidden error.
          VL-Time-Field: "timestamp"
          VL-Stream-Fields: "container,ns"  #<-- UX wise best to only have short names & 2 max (also only use keys with low cardinality) (query optimization)
          VL-Msg-Field: "message"
          AccountID: "0"
          ProjectID: "0"
    victoria_logs_db_sink_for_conventionalized_kube_event_logs:
      inputs: [ conventionalized_kube_event_logs ]  #<-- best to only send 1 input per vl_log_sink, so they can have diff VL-Stream-Field values
      type: elasticsearch   #<-- The Bulk API algorithm invented by elasticsearch is the most efficient option available
      api_version: v8
      compression: gzip
      mode: bulk
      endpoints:
      - http://vl-victoria-logs-single-server:9428/insert/elasticsearch/
      healthcheck:
        enabled: false   #<-- recommended per VL's docs: https://docs.victoriametrics.com/victorialogs/data-ingestion/vector/
      request:  #<-- based on example config of 'helm show values oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single'
        headers: #v--Important: don't put spaces between these CSV values, or it'll cause a hidden error.
          VL-Time-Field: "timestamp"
          VL-Stream-Fields: "obj_kind,event_ns"  #<-- UX wise best to only have short names & 2 max (also only use keys with low cardinality) (query optimization)
          VL-Msg-Field: "message"
          AccountID: "0"
          ProjectID: "0"
