# Referenced by:
# * ./config/baseline_envs_eks_config.ts's deploy_essentials()
#   which:
#   * Does last min injection of value into variable of this templatized_partial_helm_values.yaml file
#     (templatized variable injection occurs for enableTCP6 (true or false)
#   * stores it into a config object
# * ./lib/Frugal_Observability/deploy_vm_logs_custom_stack.ts
#   which:
#   * merges the baseline & override helm values
#   * used the merged helm values to deploy
########################################################################################################
# About:
# * This configures victoria logs single db (which is used to store kube event logs & pod logs)
# * There should be no need to change this baseline config
# * The intent is for this to represent a relatively complete (templatized) config, and additional files
#   can be supplied as config overrides.
#     // v-- can be run to show all possible values
#    // helm repo add vm https://victoriametrics.github.io/helm-charts/ && helm repo update vm && helm show values vm/victoria-logs-single
#        //Access Proxy Command:
#        //* kubectl port-forward service/vl-victoria-logs-single-server -n=observability 9428:9428
#        //Browser Access:
#        //* http://localhost:9428/select/vmui/
# * https://vector.dev/docs/reference/configuration/
# * https://github.com/vectordotdev/helm-charts/blob/vector-0.49.0/charts/vector/values.yaml
# * https://docs.victoriametrics.com/helm/victoria-logs-single/
########################################################################################################
server:
# v-- Purposefully not using pod level HTTPS, because it breaks kubectl port-forward
#  extraVolumes:
#  - name: https-cert
#    secret:
#      secretName: "https-cert-for-vl-victoria-logs-single-server" #<-- generated by cert-manager
#  extraVolumeMounts:
#  - name: https-cert
#    mouthPath: "/etc/ssl/certs"
#    readOnly: true
#  service:
#    servicePort: "9443" #<-- overrideing default un-encrypted port 9428
#    targetPort: "9443"
  extraArgs: # https://docs.victoriametrics.com/victorialogs/#list-of-command-line-flags
    enableTCP6: TEMPLATIZED_VARIABLE_IPV6_ENABLED #<-- find and replace will occur (using typescript logic)
    #           ^-- default config will substitue in true, which enables application level IPv6 support
    #               If false, then pods with IPv6 IPs would fail readiness and liveness probes
    httpListenAddr: "9428"
    tls: false #<-- setting to true will break kubectl port-forward, thus false is correct value
    # tlsCertFile: "/etc/ssl/certs/tls.crt"
    # tlsKeyFile: "/etc/ssl/certs/tls.key"
  retentionPeriod: "31d" # (Possible units characters: h(ours), d(ays), w(eeks), m(onths), y(ears))
  persistentVolume:
    size: "20Gi" # Recommendation: Never change this value (will error) & leave 20Gi as default,
                 # when you want to size up don't do so using declarative helm values
                 # resize up using the following 2 imperative kubectl commands, against pre-existing pvc object.
                 # kubectl -n=observability patch pvc server-volume-vl-victoria-logs-single-server-0 --patch '{ "spec": { "resources": { "requests": { "storage": "21Gi"} } } }'
                 # kubectl -n=observability rollout restart sts/vl-victoria-logs-single-server
                 # (pvc resize will complete after pod restarts)
                 # (Reason for recommendation is you can scale up but you can't scale down. + editing value will result in errors)
  resources:
    requests:
      cpu: "100m"
      memory: "192Mi"
    limits:
      memory: "4Gi"
  serviceMonitor:
    enabled: true #<--deploys config snippet, vm-operator uses to configure collection of metrics,
                  #   which are used by "VictoriaLogs - single-node" Grafana Dashboard.

