# Referenced by:
# * ./config/baseline_envs_eks_config.ts's deploy_essentials()
#   which:
#   * Does last min injection of value into variable of this templatized_helm_values.yaml file
#     (templatized variable injection occurs for IPV6 Compatibility Boolean Variable)
#   * stores it into a Javascript config object
########################################################################################################
# About:
# * VMKS stands for Victoria Metrics Kubernetes Stack
#   https://docs.victoriametrics.com/helm/victoria-metrics-k8s-stack
# Docs:
#         // helm repo add vm https://victoriametrics.github.io/helm-charts || helm repo update vm && helm show values vm/victoria-metrics-k8s-stack
#        // https://github.com/VictoriaMetrics/helm-charts/tree/master/charts
########################################################################################################
victoria-metrics-operator:
  enabled: true
  env:
  - name: "VM_ENABLETCP6" #<-- adds necessary IPv6 compatibility flags to all resources managed by vm operator
    value: "TEMPLATIZED_VARIABLE_IPV6_ENABLED" #<-- find and replace will occur (using typescript logic) (default config will be "true")
  extraArgs:
    controller.prometheusCRD.resyncPeriod: 1m  #(Makes prom to vm CR conversion more reliable)
  resources:
    requests:
      cpu: 2m
      memory: 42Mi
    limits:
      memory: 1Gi
kube-state-metrics: # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml
  enabled: true # <--deploys as a dependency/nested/child helm chart, such that all ^-original values-^ file's values are indented by 2
  resources:
    requests:
      cpu: 10m
      memory: 42Mi
    limits:
      memory: 256Mi
  nodeSelector:
    karpenter.sh/capacity-type: "on-demand" #<-- Valid values are "spot", "on-demand", and "reserved"
prometheus-node-exporter: # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml
  enabled: true # <--deploys as a dependency/nested/child helm chart, such that all ^-original values-^ file's values are indented by 2
  priorityClassName: "system-node-critical" #ensures daemonset is schedulable even on small nodes
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      memory: 256Mi
vmagent:        # kubectl get vmagent -n=observability
  enabled: true # <--creates a kube custom resource of type vmagent (that vm-operator will convert to vmagent deployment)
  spec:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        memory: 500Mi
    nodeSelector:
      karpenter.sh/capacity-type: "on-demand" #<-- Valid values are "spot", "on-demand", and "reserved"
vmsingle:       # kubectl get vmsingle -n=observability
  enabled: true # <--creates a kube custom resource of type vmsingle (that vm-operator will convert to vmsingle deployment)
  spec:
    retentionPeriod: "31d" #(Possible units character: h(ours), d(ays), w(eeks), m(onths), y(ears))
    extraArgs:
      maxLabelsPerTimeseries: "50" #(default value is 40, Karpenter.sh nodes generate a ton of labels, up to 45. This prevents an ignorable alert)
    resources:
      requests:
        cpu: 50m
        memory: 800Mi
      limits:
        memory: 1600Mi
    storage:
      resources:
        requests:
          storage: 20Gi #<--Recommendation: Never change this value (will error) & leave 20Gi as default, when you want to size up don't do so using declarative helm values
                        #                   resize up using the following 2 imperative kubectl command, against pre-existing pvc object.
                        #                   kubectl -n=observability patch pvc vmsingle-vmks-victoria-metrics-k8s-stack --patch '{ "spec": { "resources": { "requests": { "storage": "21Gi"} } } }'
                        #                   kubectl -n=observability rollout restart deploy/vmsingle-vmks-victoria-metrics-k8s-stack
                        #                   (pvc resize will complete after pod restarts)
                        #                   (Reason for recommendation is you can scale up but you can't scale down. + editing value will result in errors)
    nodeSelector:
      karpenter.sh/capacity-type: "on-demand" #<-- Valid values are "spot", "on-demand", and "reserved")
defaultDashboards: #<-- deploys ConfigMaps containing dashboards as JSON, that grafana sidecar will auto load / auto import as IaC Managed Dashboards
  enabled: true
  dashboards: #v-- disabling 3 that don't work with EKS due to managed ctrl plane, to remove 3 empty dashboards
    etcd:
      enabled: false
    kubernetes-controller-manager:
      enabled: false
    kubernetes-scheduler:
      enabled: false
    grafana-overview:
      enabled: false #<-- not useful
    kubernetes-kubelet:
      enabled: true
    kubernetes-system-api-server:
      enabled: true
    kubernetes-system-coredns:
      enabled: true
    kubernetes-views-global:
      enabled: true
    kubernetes-views-namespaces:
      enabled: true
    kubernetes-views-nodes:
      enabled: true
    kubernetes-views-pods:
      enabled: true
    node-exporter-full:
      enabled: true
    victoriametrics-operator:
      enabled: true
    victoriametrics-single-node:
      enabled: true
    victoriametrics-vmagent:
      enabled: true
    victoriametrics-vmalert:
      enabled: true
defaultRules: #<-- creates vmrule objects, a few that aren't applicable to EKS have been disabled (avoids no data collected warning)
  groups:
    etcd:
      create: false
    kubeScheduler:
      create: false
    kubernetesSystemScheduler:
      create: false
    kubernetesSystemControllerManager:
      create: false
    kubernetesSystemKubelet:
      create: false #<--a slightly customized version gets created by cdk
    kubelet:
      create: false
    k8sPodOwner:
      create: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
grafana:        # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
  enabled: true # <--deploys as a dependency/nested/child helm chart, such that all ^-original values file values are indented by 2
  ingress:
    enabled: false
    hosts:
    - localhost:3000 #value's still read by templatized alertmanager even when enabled is false
  nodeSelector:
    karpenter.sh/capacity-type: "on-demand" #<-- Valid values are "spot", "on-demand", and "reserved"
  sidecar:
    dashboards:
      enabled: true  # <-- enable sidecar that auto loads grafana dashboards as code embedded as json in configmaps
      label: grafana_dashboard
      labelValue: "1" # auto load dashboards stored in configmaps with kubernetes label matching this key value pair
    resources: # (of grafana's config reloader sidecar container)
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 512Mi
  resources: # (of grafana's main container)
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      memory: 1024Mi
  admin:
    existingSecret: "grafana-admin-basic-auth"
    userKey: "username" #(reads value of specified key existing in a kubernetes secret)
    passwordKey: "password" #(reads value of specified key existing in a kubernetes secret)
  grafana.ini:
    auth.anonymous:
      enabled: true 
      org_name: "Main Org." #<-- default org
      org_role: "Viewer" #<-- kube forward users default to viewer access & can login for admin edit access
    unified_alerting: #<-- Grafana has a built in alert manager, disabling to avoid confusion & enforce IaC based alerts
      enabled: false  #<-- Use vmalert instead
    plugins: #Plugin names based on URL paths on this page https://grafana.com/grafana/plugins/all-plugins/
      disable_plugins: "grafana-lokiexplore-app,grafana-exploretraces-app,grafana-pyroscope-app" #<-- Disabled to remove distractions, reenable if needed
      # grafana-lokiexplore-app = Drilldown/Logs (option in the GUI)
      # grafana-exploretraces-app = Drilldown/Traces (option in the GUI)
      # grafana-pyroscope-app = Drilldown/Profiles (option in the GUI)
  plugins:
  - victoriametrics-logs-datasource
  # - victoriametrics-metrics-datasource #<--intentionally commented out, in favor if built in prometheus data source
  # Plugin Name Lookup instructions
  # Step 1: Find Plugin https://grafana.com/grafana/plugins/all-plugins/
  # Step 2: https://grafana.com/grafana/plugins/victoriametrics-logs-datasource/?tab=installation
  # Step 3: Find plugin name from url path or on the pabe
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      # - name: VictoriaMetrics  #(could potentially useful for custom dashboard, supports a few additional Victoria Metric specific Queries)
      #   type: victoriametrics-metrics-datasource
      #   access: proxy
      #   url: http://vmsingle-vmks-victoria-metrics-k8s-stack.observability.svc.cluster.local:8428
      #   isDefault: false
      # For better compatibility with pre-existing dashboards, victoria metrics backend is loaded as type Prometheus
      - name: VictoriaMetrics #(Recommended for compatibility with pre-existing open source community developed dashboards)
        type: prometheus
        access: proxy
        url: http://vmsingle-vmks-victoria-metrics-k8s-stack.observability.svc.cluster.local.:8428
        isDefault: false
      - name: VictoriaLogs
        type: victoriametrics-logs-datasource
        access: proxy
        url: http://vl-victoria-logs-single-server.observability.svc.cluster.local.:9428
        isDefault: false
alertmanager:
  enabled: true
  spec:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 500Mi
    nodeSelector:
      karpenter.sh/capacity-type: "on-demand" #<-- Valid values are "spot", "on-demand", and "reserved"
vmalert:
  enabled: true
  spec:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 500Mi
    nodeSelector:
      karpenter.sh/capacity-type: "on-demand" #<-- Valid values are "spot", "on-demand", and "reserved"
